run: compile
	./camilo_garcia_260657037
compile: clean camilo_garcia_260657037.cpp
	g++ camilo_garcia_260657037.cpp -o camilo_garcia_260657037
clean:
	rm camilo_garcia_260657037 2> /dev/null || echo > /dev/null
